version: ~> 1.0
os: linux
dist: xenial
language: generic

before_install:
  - echo 'In repo..'

import:
  source: qasimabdullah404/travis-build-config-import-file:before_install.yml@main

script:
  true